### PR TITLE
Improve user instructions

### PR DESCRIPTION
**Pull request by jaredreynolds**
## Goal
Provide clear instructions for running Strap so there is less need for hand-holding, especially for non-devs.

## Overview
- This PR will be used to iteratively improve the Strap instructions with your feedback and changes.
- Some additional instructions will be added for using a locally-downloaded box file.
- If possible, these changes should be only affect the `web` folder (i.e., no actual Strap logic changes).

## Your role
- Feel free to criticize and/or fix problems you have with the instructions.  It's an open PR so please help out!
- Invite anyone who has recent experience running Strap to provide feedback.

## Running the web site locally
~Coming soon...~  Oops, they are already contained in the readme.

/to @jtrinklein @dachew @jaredreynolds
/cc @mandarenee @stephenfowler @ctiglao

### CODE REVIEW

**Comment by jtrinklein** [comment]
@jaredreynolds Is there anything else to do for this? I would like to merge it

**Comment by jaredreynolds** [comment]
Current instruction page below.  Your comments on whether this is more helpful and what could be improved would be appreciated!

screen shot 2018-03-22 at 1 49 52 pm

**Comment by stephenfowler** [comment]
The downloaded box instructions worked and made sense. The only thing that I did run into is that you want to make sure it is done on your first run. If you try to setup the box after it has failed on the ppm step it doesn't know that it didn't work, so it won't rerun the box setup.

**Comment by jaredreynolds** [comment]
👍 I'll add a note about that under the main header.

**Comment by stephenfowler** [comment]
Sounds good. :shipit:

**Pull request merged**
